### ISSUE TITLE
Build process is still not straightforward

### ISSUE THREAD

**Issue by archbirdplus** [PixelGuys/Cubyz#241]
1. Rename `run.sh` to `debug_run.sh`.
2. Rename `run_release.sh` to `run_.sh`.

This rename should make it more clear which script users should execute, without looking into them ("The normal run option appears to be some developer thing"). The default-looking option should be the happy path for the average end-user. It might also make sense to label the run scripts with the name of the OS.

3. Add info errors for tech support, and progress meters. These can include:
* checking compiler...
* installing compiler...
* building Cubyz (with optimizations)
* Cubyz is ready!
* Launching Cubyz.

These messages should help quickly identify common scenarios in `#help-and-questions`. They should also reduce newcomers' impatience with the build process. This might lead to a suggestion for the Zig compiler project.

**Comment by IntegratedQuantum** [comment]
Good idea.
However I would prefer `debug.sh` because it's shorter.
More feedback for the user would be really good:
I'd also love to have progress bars for downloading/unzipping, but sadly the windows commands implemented it so poorly, that it made the whole download process ten times slower. So I had to disable it.

In future, hopefully we can implement a progress bar in the launcher #227
