### ISSUE TITLE
mesh network

### ISSUE THREAD

**Issue by Pantyhose-X** [PixelGuys/Cubyz#266]
overlay networking since each node is both a server and a client
overlay networking to create a direct encrypted tunnel between two nodes even if they’re both behind firewalls. Each node doesn’t even need to know the other’s IP address before starting the connection.

[Hyprspace](https://github.com/hyprspace/hyprspace#hyprspace)
[n2n](https://github.com/ntop/n2n#n2n)
[nebula](https://github.com/slackhq/nebula)
[qaul](https://github.com/qaul/qaul.net)

P2P
[Hypercore Protocol](https://github.com/hypercore-protocol) and [pinecone](https://github.com/matrix-org/pinecone) and [libp2p](https://libp2p.io/) and [devp2p](https://github.com/ethereum/devp2p)
WebRTC
bittorrent
[gemini](https://gemini.circumlunar.space/)
[Earthstar](https://earthstar-project.org/)
[Pigeon](https://tildegit.org/PigeonProtocolConsortium/Protocol-Spec)
[geneva Protocol](https://github.com/Kkevsterrr/geneva)

**Comment by IntegratedQuantum** [comment]
I don't think this makes sense for a small-scale multiplayer game like Cubyz.
A centralized server is needed in order to store a consistent game state. Otherwise it would be possible to get conflicting game states and I don't want to deal with that.
Additionally, a decentralized system would require a lot of additional work and storage, since everyone would be storing copies of the information.

By the way, Cubyz is already in some ways peer to peer:
There is no authentication server.
The game server can be behind a firewall, due to using holepunching.
