### ISSUE TITLE
Add fog occlusion for biome fog

### ISSUE THREAD

**Issue by ikabod-kee** [PixelGuys/Cubyz#592]

**Comment by IntegratedQuantum** [comment]
So it wouldn't draw stuff behind the fog?

**Comment by IntegratedQuantum** [comment]
I don't think this is feasable.
A simple heuristic (like assuming the biome fog density as the highest density) won't work because placed blocks can have less dense fog.
So we only know the fog density of pixel after transparent rendering, and since that's the last stage we cannot cull anything based on that.
