### ISSUE TITLE
Volume slider dB/% is inaccurate

### ISSUE THREAD

**Issue by Moonyol** [PixelGuys/Cubyz#641]
![image](https://github.com/user-attachments/assets/700dd186-d331-4c35-88cb-dd3dc1b560e4)
A difference of -10dB halves the perceived volume of the sound but the slider says it's 32% which would be -16dB.
https://www.reddit.com/r/audioengineering/comments/y7bfpf/the_scale_of_decibels/
Also dB = 10log_2(slider %) would be better because people are most likely to have it towards the right but that's where moving the slider a little changes the sound a lot.

**Comment by IntegratedQuantum** [comment]
Here I'm displaying % amplitude. And for amplitude 20 dB are a factor of 10. So the dezibel is correctly calculated.

I used % amplitude, because that's how the loudness is measured in many other applications and games.
I put it there mainly to show the logarithmic nature of the slider.

> Also dB = 10log_2(slider %) would be better because people are most likely to have it towards the right but that's where moving the slider a little changes the sound a lot.

I don't think this is a problem. In fact your proposal, to have a slider linear in the amplitude, creates the opposite problem.
For example in terraria which has such a system, I found myself struggling a lot because the perceived difference between 2% and 3% amplitude is so much larger than the perceived difference between 99% and 100%.
In Cubyz 3% is right in the middle of the slider making it easier to adjust.
