### ISSUE TITLE
Convert recipe files to zon

### ISSUE THREAD

**Issue by ikabod-kee** [PixelGuys/Cubyz#767]

**Comment by IntegratedQuantum** [comment]
We could do it like this, but it does seem rather clunky compared to the current one:
```zig
.{
	.{ // Recipe 1
		.input = .{"4 cubyz:oak_planks"},
		.output = .{"cubyz:workbench"},
	},
	.{ // Recipe 2
		.input = .{"4 cubyz:birch_planks"},
		.output = .{"cubyz:workbench"},
	},
	.{ // And maybe a short form, if there is only one element:
		.input = "4 cubyz:birch_planks",
		.output = "cubyz:workbench",
	},
}
```

**Comment by IntegratedQuantum** [comment]
I guess we could do something like this, too:
```
.{
	.@"cubyz:workbench" = .{"4 cubyz:oak_planks"},
	.@"cubyz:torch" = .{"cubyz:oak_planks", "cubyz:coal"},
}
```
The problem with this is that the items on the left cannot contain duplicate entries, so you'd have to make one file for each wood type (which might be a good idea anyways)

Honestly I kind of like this "result = ingredients" style.

**Comment by IntegratedQuantum** [comment]
Isn't that a long-term goal anyways? Anyways, it would probably be a a separate type, like this:
```zig
	.@"cubyz:stone_bricks" = .{"cubyz:stone", .{
		.type = .chisel,
		.requiredPower = 5,
		.damage = 1,
	}},
```

**Comment by IntegratedQuantum** [comment]
Don't worry, I'll do it all, after I do the necessary code changes.

**Comment by IntegratedQuantum** [comment]
I'm not so sure about this anymore. I think it would cause too many problems that the left hand side cannot contain duplicate entries. Furthermore I don't like how clunky it still is with all the @ signs and quotation marks.
Maybe we can find a better format? Or should we just keep using the custom one (I could also try to make a few improvements to it)?

**Comment by IntegratedQuantum** [comment]
Alright I thought about it some more and looked at how minecraft solves it, and I don't think the custom format is the way to go, since it will be rather difficult to add support for tools like chisels.

Honestly, I would probably just go with the clunky version from the beginning because it would also have space for other data, like for example specifying a crafting station.

And actually the clunkyness isn't too bad, since you'll copy paste it anyways.
