### ISSUE TITLE
Raytracing

### ISSUE THREAD

**Issue by jujubeja** [PixelGuys/Cubyz#835]
Just like this Zig library Raytracing effect https://github.com/zig-gamedev/zig-gamedev

> The most impressive feature of Minecraft is probably its Raytracing. I hope that Cubyz Raytracing effects will surpass Minecraft's while consuming less resources.

**Comment by IntegratedQuantum** [comment]
I have investigated raytracing in the past, but it is too slow on low-end hardware and integrated GPUs (which I want to keep supporting).

Furthermore I do not want to maintain two completely different rendering backends.

But not all hope is lost. Since Cubyz is open source, anyone could maintain a 3rd party implementation of Cubyz with raytracing.
